name: CI/CD Pipeline

on:
  push:
    # "main" ke saath apni current branch "setup-automation" lazmi add karein
    branches: [ "main", "setup-automation" ]
  pull_request:
    branches: [ "main", "setup-automation" ]
  # Is line se aap GitHub par button daba kar bhi workflow chala saken ge
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'zainabkhan20'
          # Yaad rakhein: GitHub Secrets mein "ZAINABKHAN" ke naam se token hona chahiye
          password: ${{ secrets.ZAINABKHAN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Aapka image tag
          tags: zainabkhan20/devops-assignment:latest